import { Product } from '@/types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Linen Oversized Shirt',
    slug: 'linen-oversized-shirt',
    price: 4500,
    original_price: 5500,
    images: [
      'https://images.unsplash.com/photo-1594938298603-c8148c4b4c3e?w=800',
      'https://images.unsplash.com/photo-1603251579431-8041402bdeda?w=800',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    category: 'tops',
    description: 'Relaxed fit linen shirt. Perfect for the warm Sri Lankan climate. Breathable, lightweight, and effortlessly stylish.',
    in_stock: true,
    featured: true,
    tags: ['linen', 'oversized', 'casual'],
  },
  {
    id: '2',
    name: 'Wide Leg Trousers',
    slug: 'wide-leg-trousers',
    price: 5800,
    images: [
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800',
      'https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'bottoms',
    description: 'High-waisted wide leg trousers. Tailored but relaxed. A wardrobe essential.',
    in_stock: true,
    featured: true,
    tags: ['trousers', 'wide-leg', 'minimal'],
  },
  {
    id: '3',
    name: 'Slip Midi Dress',
    slug: 'slip-midi-dress',
    price: 6200,
    original_price: 7500,
    images: [
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800',
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    category: 'dresses',
    description: 'Satin slip midi dress. Effortless elegance for day to evening.',
    in_stock: true,
    featured: true,
    tags: ['dress', 'satin', 'elegant'],
  },
  {
    id: '4',
    name: 'Cotton Crop Top',
    slug: 'cotton-crop-top',
    price: 2800,
    images: [
      'https://images.unsplash.com/photo-1485230895905-ec40ba36b9bc?w=800',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    category: 'tops',
    description: 'Clean, minimal cotton crop top. The perfect layering piece.',
    in_stock: true,
    featured: false,
    tags: ['cotton', 'crop', 'minimal'],
  },
  {
    id: '5',
    name: 'Linen Co-ord Set',
    slug: 'linen-coord-set',
    price: 8900,
    images: [
      'https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?w=800',
    ],
    sizes: ['S', 'M', 'L'],
    category: 'sets',
    description: 'Matching linen shirt and trouser set. Buy together or separately.',
    in_stock: true,
    featured: true,
    tags: ['linen', 'coord', 'set'],
  },
  {
    id: '6',
    name: 'Knit Cardigan',
    slug: 'knit-cardigan',
    price: 5200,
    images: [
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'tops',
    description: 'Soft oversized knit cardigan. Layer it over everything.',
    in_stock: false,
    featured: false,
    tags: ['knit', 'cardigan', 'layering'],
  },
]

export const categories = ['all', 'tops', 'bottoms', 'dresses', 'sets']
